# Generated by Django 3.2.6 on 2021-12-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0002_auto_20211220_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='types',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
