# Generated by Django 3.2.6 on 2021-12-23 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CancerAid', '0005_message_room_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Discussion',
        ),
        migrations.RenameModel(
            old_name='Topic',
            new_name='DiscussionTopic',
        ),
    ]
