# Generated by Django 3.2.6 on 2022-01-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0008_address_ambudetails_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambudetails',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
