# Generated by Django 3.2.6 on 2022-01-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0009_ambudetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambudetails',
            name='name',
            field=models.CharField(auto_created=True, max_length=200, null=True),
        ),
    ]
