# Generated by Django 3.2.6 on 2022-01-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0010_alter_ambudetails_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='ambudetails',
            old_name='name',
            new_name='current_address',
        ),
        migrations.RenameField(
            model_name='ambudetails',
            old_name='address',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='address',
            new_name='district',
        ),
    ]
