# Generated by Django 3.2.6 on 2022-01-01 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0011_auto_20220102_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambudetails',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CancerAid.patient'),
        ),
    ]
