# Generated by Django 3.2.6 on 2022-01-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0012_ambudetails_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambudetails',
            name='patient',
        ),
    ]
