# Generated by Django 3.2.6 on 2022-01-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0015_doctor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ord',
            old_name='desc',
            new_name='problem',
        ),
    ]
