# Generated by Django 3.2.6 on 2022-01-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0016_rename_desc_ord_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ord',
            name='posting_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
