# Generated by Django 3.2.6 on 2022-01-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0021_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BkashPayment',
        ),
    ]
