# Generated by Django 3.2.6 on 2022-01-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0023_bkashpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bkashpayment',
            old_name='fh',
            new_name='financial_help',
        ),
        migrations.RenameField(
            model_name='bkashpayment',
            old_name='mnaq',
            new_name='medicine_name_and_quentity',
        ),
    ]
