# Generated by Django 3.2.6 on 2022-01-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0024_auto_20220108_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BkashPayment',
        ),
    ]
