# Generated by Django 3.2.6 on 2022-01-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0025_delete_bkashpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('option', models.CharField(choices=[('Donation', 'Donation'), ('Doctor Visit Cost', 'Doctor Visit Cost'), ('Medicine Bill', 'Medicine Bill'), ('Ambulance Cost', 'Ambulance Cost')], max_length=200)),
                ('medicine_name_and_quentity', models.CharField(max_length=100, null=True)),
                ('bkashNumber', models.CharField(max_length=20)),
                ('bkashTransaction', models.CharField(max_length=512)),
                ('financial_support', models.CharField(choices=[('Yes I Have', 'Yes I have'), ('No I dont need', 'No I dont need')], max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
