# Generated by Django 3.2.6 on 2022-01-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0028_alter_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(choices=[('You will get 30 percent discount for all services', 'You will get 30 percent discount for all services'), ('You will get 50 percent discount for all services', 'You will get 50 percent discount for all services'), ('You will get 70 percent discount for all services', 'You will get 70 percent discount for all services'), ('Sorry there is no discount for you', 'Sorry there is no discount for you')], max_length=200, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CancerAid.patient')),
            ],
        ),
    ]
