# Generated by Django 3.2.6 on 2022-01-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0030_auto_20220108_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='FS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('reason_why_you_need_this', models.TextField()),
            ],
        ),
    ]
