# Generated by Django 3.2.6 on 2022-01-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CancerAid', '0031_fs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashpayment',
            name='medicine_name_and_quentity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
