from django.contrib import admin
from django.urls import path
from CancerAid.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='homepage'),
    path('user/', userpage, name="userpage"),
    path('signup', handleSignUp, name="handleSignUp"),
    path('login', handeLogin, name="handleLogin"),
    path('logout', handelLogout, name="handleLogout"),
    path('medicine', medicinepage, name='medicinepage'),
    path('doctor', doctorpage, name='doctorpage'),
    path('dashboard', dashboardpage, name='dashboardpage'),
    path("patient/<str:pk>/", patientpage, name='patientpage'),
    path("update_order/<str:pk>/",updateOrder,name='updateOrder'),
    path("delete/<str:pk>/",deleteOrder,name='deleteOrder'),
    path("order1_form/<str:pk>",createOrder,name='createOrder'),
    path("contect",contect,name='contect'),
    path("comments/", comments,name='comments'),
    path("Lungcancer/", Lung,name='Lung'),
    path("addmedicine",AddMedicine,name='AddMedicine'),
    path('discussion/<str:pk>/', discussion, name="discussion"),
    path('discussion_topic/', discussion_topicpage, name="discussion_topicpage"),
    path('discussion_form/', createDiscussion, name="createDiscussion"),
    path('update-discussion/<str:pk>/', updateDiscussion, name="updateDiscussion"),
    path('delete-discussion/<str:pk>/', deleteDiscussion, name="deleteDiscussion"),
    path('delete-message/<str:pk>/', deleteMessage, name="deleteMessage"),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),  name="reset_password"),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), name="password_reset_complete"),
    path('ambu', addambu, name="addambu"),
    path('<int:pk>/', ambuupdate, name='ambuupdate'),
    path('ajax/load-hospitals/', load_hospitals, name='ajax_load_hospitals'), # AJAX
    path("order3_form/<str:pk>",createOrd,name='createOrd'),
    path('doctorsignup', doctorSignUp, name="doctorSignUp"),
    path('doctorsite/', doctoruserpage, name="doctoruserpage"),
    path("update_ord/<str:pk>/",updateOrd,name='updateOrd'),
    path('adddoctor', addDoctor, name="addDoctor"),
    path('PatientRecord', PatientRecordpage, name="PatientRecordpage"),
    path("Stomach Cancer/", Stomach,name='Stomach'),
    path("Bladder Cancer/", Bladder,name='Bladder'),
    path("Breast Cancer/", Breast,name='Breast'),
    path("Liver Cancer/", Liver,name='Liver'),
    path("Ovarian Cancer/", Ovarian ,name='Ovarian'),
    path("videos/", Videos ,name='Videos'),
    path("about/", About,name='About'),
    path('bkashpayment', payment, name="payment"),
    path('manager', manager, name="manager"),
    path('FS', FSpage, name="FS"),
    path("update_medicine/<str:pk>/",updateMedicine,name='updateMedicine'),
    path("delete_medicine/<str:pk>/",deleteMedicine,name='deleteMedicine'),
    path("update_doctor/<str:pk>/",updateDoctorInfo,name='updateDoctorInfo'),
    path("delete_doctor/<str:pk>/",deleteDoctorInfo,name='deleteDoctorInfo'),
     path("update_payment/<str:pk>/",updatePayStatus,name='updatePayStatus'),
]
